### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by SUDestroyer** [Lvenizerv/Aurora#8]
When running the install command (pip install -r requirements.txt) it just doesn't wanna work
<img width="202" alt="Screenshot 2022-06-14 110234" src="https://user-images.githubusercontent.com/78056048/173623570-e0fa5d03-7a71-4e60-9be3-10295b160adc.png">
Any help would be appreciated

**Comment by SUDestroyer** [comment]
It's now just telling me its not a valid command
<img width="334" alt="Screenshot 2022-06-14 123408" src="https://user-images.githubusercontent.com/78056048/173641032-5a15f16d-b91c-4930-828a-2b8932ad1428.png">

**Comment by cx622** [comment]
Did you install python?

**Comment by SUDestroyer** [comment]
Yes, I have python installed
<img width="266" alt="Screenshot 2022-06-14 134106" src="https://user-images.githubusercontent.com/78056048/173664877-94ae0e83-f3d1-4726-be2c-56ca625f1ae8.png">

**Comment by TheBaconPug** [comment]
> Yes, I have python installed
> <img width="266" alt="Screenshot 2022-06-14 134106" src="https://user-images.githubusercontent.com/78056048/173664877-94ae0e83-f3d1-4726-be2c-56ca625f1ae8.png">
> 

py -m pip install -r requirements.txt

**Comment by SUDestroyer** [comment]
> > Yes, I have python installed
> > <img alt="Screenshot 2022-06-14 134106" width="266" src="https://user-images.githubusercontent.com/78056048/173664877-94ae0e83-f3d1-4726-be2c-56ca625f1ae8.png">
> 
> py -m pip install -r requirements.txt

It's still giving me issues
<img width="509" alt="Screenshot 2022-06-14 202708" src="https://user-images.githubusercontent.com/78056048/173716921-738d3af2-d8ca-428e-8fa7-639fb0799585.png">

**Comment by TheBaconPug** [comment]
> > > Yes, I have python installed
> > > <img alt="Screenshot 2022-06-14 134106" width="266" src="https://user-images.githubusercontent.com/78056048/173664877-94ae0e83-f3d1-4726-be2c-56ca625f1ae8.png">
> > 
> > py -m pip install -r requirements.txt
> 
> It's still giving me issues
> <img width="509" alt="Screenshot 2022-06-14 202708" src="https://user-images.githubusercontent.com/78056048/173716921-738d3af2-d8ca-428e-8fa7-639fb0799585.png">
> 

Install pip

**Comment by SUDestroyer** [comment]
> py -m pip install -r requirements.txt

Ok, I've installed pip (hopefully) and now it can't find the file for some reason
<img width="536" alt="Screenshot 2022-06-14 205056" src="https://user-images.githubusercontent.com/78056048/173719368-84b5b85d-c671-48b8-84e2-bb0ac78d90d5.png">

**Comment by TheBaconPug** [comment]
> > py -m pip install -r requirements.txt
> 
> Ok, I've installed pip (hopefully) and now it can't find the file for some reason
> <img width="536" alt="Screenshot 2022-06-14 205056" src="https://user-images.githubusercontent.com/78056048/173719368-84b5b85d-c671-48b8-84e2-bb0ac78d90d5.png">
> 

You're not in the folder with the files in it

**Comment by SUDestroyer** [comment]
> > > py -m pip install -r requirements.txt
> > 
> > 
> > Ok, I've installed pip (hopefully) and now it can't find the file for some reason
> > <img alt="Screenshot 2022-06-14 205056" width="536" src="https://user-images.githubusercontent.com/78056048/173719368-84b5b85d-c671-48b8-84e2-bb0ac78d90d5.png">
> 
> You're not in the folder with the files in it

Ok, so how would I do that?

**Comment by TheBaconPug** [comment]
> ?

https://m.youtube.com/watch?v=MBBWVgE0ewk

**Comment by SUDestroyer** [comment]
Thanks for the help, got it working
